CREATE TABLE freedb_pruebatecnica.usuario (
  USUARIOID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(100) DEFAULT NULL,
  FECHANACIMIENTO DATETIME DEFAULT NULL,
  SEXO VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (USUARIOID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

CREATE DEFINER=`freedb_username`@`%` PROCEDURE `USUARIOCRUD`(IN OPERATION CHAR(1), IN IUSUARIOID INT, IN INOMBRE VARCHAR(100), IN IFECHANACIMIENTO DATETIME, IN ISEXO VARCHAR(1))
BEGIN
  CASE OPERATION

        WHEN 'L' THEN
            SELECT USUARIOID, NOMBRE, FECHANACIMIENTO, SEXO
            FROM usuario
            ORDER BY USUARIOID;

        WHEN 'C' THEN
            INSERT INTO usuario (NOMBRE, FECHANACIMIENTO, SEXO)
            VALUES (NOMBRE, FECHANACIMIENTO, SEXO);
            SELECT LAST_INSERT_ID() AS USUARIOID;

        WHEN 'R' THEN
            SELECT USUARIOID, NOMBRE, FECHANACIMIENTO, SEXO
            FROM usuario
            WHERE USUARIOID = IUSUARIOID;

        WHEN 'U' THEN
            UPDATE usuario
            SET
                NOMBRE = INOMBRE,
                FECHANACIMIENTO = IFECHANACIMIENTO,
                SEXO = ISEXO
            WHERE USUARIOID = IUSUARIOID;
            SELECT ROW_COUNT() AS filas_afectadas;

        WHEN 'D' THEN
            DELETE FROM usuario
            WHERE USUARIOID = IUSUARIOID;
            SELECT ROW_COUNT() AS filas_afectadas;

        ELSE

            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Operacion invalida. Use L, C, R, U, D.';
    END CASE;
END